# Generated by Django 3.2.15 on 2022-09-29 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='document',
            name='functions',
        ),
        migrations.RemoveField(
            model_name='document',
            name='result',
        ),
    ]
