# Generated by Django 3.2.15 on 2022-09-29 10:05

from django.db import migrations, models
from django.conf import settings
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220929_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='contract',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='functions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='result',
            field=models.TextField(default='{}'),
        ),

        migrations.AlterField(
            model_name='document',
            name='contract',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='result',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.CreateModel(
            name='UploadContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.JSONField(blank=True, default=dict, null=True)),
                ('functions', models.TextField(blank=True, null=True)),
                ('contract', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OnlineContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=40)),
                ('result', models.JSONField(blank=True, default=dict, null=True)),
                ('functions', models.TextField(blank=True, null=True)),
                ('contract', models.TextField()),
            ],
        ),
    ]
