FROM octahub.8lab.cn:5000/l4-triathon/core-base:v1
COPY sources.list /etc/apt/sources.list
WORKDIR /usr/local/coreslither/
RUN solc-select install 0.4.26
RUN solc-select install 0.5.16
RUN solc-select install 0.6.11
RUN solc-select install 0.7.6
RUN solc-select install 0.8.16
RUN solc-select use 0.8.16 
ADD coreslither /usr/local/coreslither
CMD python3 /usr/local/coreslither/coreslither/handler.py 


