FROM octahub.8lab.cn:5000/l4-triathon/core-base:v1
COPY sources.list /etc/apt/sources.list
WORKDIR /usr/local/corethril/
ADD corethril /usr/local/corethril
RUN solc-select install 0.4.26
RUN solc-select install 0.5.16
RUN solc-select install 0.6.11
RUN solc-select install 0.7.6
RUN solc-select install 0.8.16
RUN solc-select use 0.8.16
CMD python3 /usr/local/corethril/corethril/handler.py


